/*
 * This header is generated by classdump-dyld 1.0
 * on Friday, February 12, 2021 at 12:36:27 AM Eastern European Standard Time
 * Operating System: Version 14.4 (Build 18D52)
 * Image Source:
 * /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias
 * Limneos.
 */

#import <SpringBoard/SBSecureWindow.h>
#import <SpringBoard/SpringBoard-Structs.h>

@interface SBReachabilityWindow : SBSecureWindow

- (id)initWithWallpaperVariant:(long long)arg1;
- (BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
- (id)view;
@end